name: authorize
description: Authorize github
inputs:
  app_private_key:
    description: "Github app private key"
    required: true
  github_client_id:
    description: "Github app client id"
    required: true
  github_installation_id:
    description: "Github installation id"
    required: true
  export_environment_variables:
    description: "Export token as environment variable (GH_TOKEN)"
    default: 'false'

outputs:
  token:
    description: "github token"
    value: ${{ steps.auth.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: Authorize GitHub
      id: auth
      shell: bash
      env:
        APP_PRIVATE_KEY: ${{ inputs.app_private_key }}
        # https://github.blog/changelog/2024-05-01-github-apps-can-now-use-the-client-id-to-fetch-installation-tokens/
        GITHUB_APP_IDENTIFIER: ${{ inputs.github_client_id }}
        GITHUB_INSTALLATION_ID: ${{ inputs.github_installation_id }}
      run: |
        token=$(python ${{ github.action_path }}/main.py)
        echo "token=$token" >> $GITHUB_OUTPUT

    - name: Export Token
      if: inputs.export_environment_variables != 'false'
      shell: bash
      run: |
        echo "GH_TOKEN=${{ steps.auth.outputs.token }}" >> $GITHUB_ENV
